name: ✨ Request a feature
description: Request a new feature to implement in OctoPrint
title: "[Request] "
body:
  - type: markdown
    attributes:
      value: >
        **Thank you for wanting to request a feature in OctoPrint!**


        Before you go ahead with your request, please first consider if it wouldn't be
        better suited for a plugin. As a general rule of thumb, any feature that is only
        of interest to a small sub group should be moved into a plugin. Only such features
        that are of interest to a majority of OctoPrint's users will be implemented as
        part of the core itself.

  - type: textarea
    attributes:
      label: The problem
      description: Please provide a clear and concise description of what kind of problem your requested feature is supposed to solve. Eg, "I'm always frustrated when [...]".
  - type: textarea
    attributes:
      label: Proposed solution
      description: Please provide a clear and concise description of what you want to happen. Explain why it needs to be included in OctoPrint's core and can't become a plugin.
    validations:
      required: true
  - type: textarea
    attributes:
      label: Alternative solutions
      description: A clear and concise description of any alternative solutions or features you've considered.
  - type: textarea
    attributes:
      label: Additional context
      description: Add any other context or screenshots about the feature request here.
